config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
 
  get 'posts/index'
  get 'posts/show/:slug', to: 'posts#show', as: :posts_show
  get 'posts/new'
  post 'posts', to: 'posts#create', as: :posts
  get 'posts/edit/:slug', to: 'posts#edit', as: :posts_edit
  patch 'posts/edit/:slug', to: 'posts#update', as: :posts_update
  delete 'posts/delete/:slug', to: 'posts#destroy', as: :posts_destroy
  
  resources :categories

  root                to: 'pages#index'
  get   '/contact',   to: 'pages#contact',      as: :contact_page
  post  '/contact',   to: 'pages#contact_post', as: :contact_post
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
# == Schema Information
#
# Table name: categories
#
#  id          :integer          not null, primary key
#  name        :string
#  description :string
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Category < ApplicationRecord
  has_many :posts
end

app/models/post.rb
# == Schema Information
#
# Table name: posts
#
#  id          :integer          not null, primary key
#  title       :string
#  content     :text
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  rating      :string
#  slug        :string
#  category_id :integer
#

class Post < ApplicationRecord
    belongs_to          :category

    before_validation   :check_slug
    before_save         :titlize_title

    validates           :title,       presence: true
    validates           :slug,        uniqueness: true
    validates           :content,     presence: true
    validates           :rating,      numericality: true

    private
    def check_slug
      self.slug = self.title.parameterize
    end

    def titlize_title
      self.title = self.title.titleize
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
    before_action :set_category, except: [:index, :new, :create]
    def index
        @categories = Category.all
    end

    def create
        @category = Category.new(category_params)
        if @category.save
            redirect_to categories_path 
        else
            render :new
        end
    end

    def new
        @category = Category.new
    end

    def edit
    end

    def show
    end

    def update
        if @category.update(category_params)
            redirect_to category_path
        else
            render :edit
        end
    end

    def destroy
        if @category.destroy!
            redirect_to :back
        end
    end

    private
    def set_category
        @category = Category.find(params[:id])
    end
    def category_params
        params.require(:category).permit(:name, :description)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
    @today = Time.now
  end

  def contact
    @message = 'AB17 - Ruby on Rails 101 Sınıfı'
  end

  def contact_post
    @params = params['/contact']

    render "pages/contact"
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
      @posts = Post.all.reverse
  end

  def show
    post_slug = params[:slug]
    @post = Post.find_by_slug(post_slug)
  end

  def new
    @post = Post.new
    @categories = Category.all.map{ |c| [c.name, c.id] }
  end

  def create
    @post = Post.new(post_params)
    if @post.save
        redirect_to posts_index_path
    else
        render :new
    end
  end

  def edit
    post_slug = params[:slug]
    @post = Post.find_by_slug(post_slug)
    @categories = Category.all.map{ |c| [c.name, c.id] }
  end

  def update
    post_slug = params[:slug]
    @post = Post.find_by_slug(post_slug)
    if @post.update(post_params)
        redirect_to posts_show_path(@post.slug)
    else
        render :edit
    end
  end

  def destroy
      post_slug = params[:slug]
      @post = Post.find_by_slug(post_slug)
      if @post.destroy!
          redirect_to :back
      end
  end

  private
    def post_params
      params.require(:post).permit(:title, :content, :rating, :category_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/categories/edit.html.erb
<h1>Kategoriyi Düzenle</h1>
<% if @category.errors.any? %>
    <p>
    <%= @category.errors.full_messages %>
    </p>
<% end %>
<%= form_for @category do |f| %>
    <%= f.text_field :name, placeholder: 'İsim' %>
    <%= f.text_field :description, placeholder: 'Açıklaması' %>
    <%= f.submit "Enter" %>
<% end %>

app/views/categories/index.html.erb
<h1>Kategoriler</h1>
<%= link_to "Yeni Kategori Oluştur", new_category_path %>
<% @categories.each do |category| %>
    <p>
        <%= link_to category.name, category_path(category) %> -
        <%= category.description %>
        <%= link_to "Düzenle", edit_category_path(category) %>
        <%= link_to "Sil", category_path(category), method: :delete, data: { confirm: "Silmek istediğinize emin misiniz?"} %>
    </p>
<% end %>

app/views/categories/new.html.erb
<h1>Yeni Kayıt Ekle</h1>
<% if @category.errors.any? %>
    <p>
    <%= @category.errors.full_messages %>
    </p>
<% end %>
<%= form_for @category do |f| %>
    <%= f.text_field :name, placeholder: 'İsim' %>
    <%= f.text_field :description, placeholder: 'Açıklama' %>
    <%= f.submit "Enter" %>
<% end %>

app/views/categories/show.html.erb
<h1><%= @category.name %></h1>
<h1><%= @category.description %></h1>

app/views/layouts/_header.html.erb
<header>
  <%= link_to 'Ana Sayfa', root_path %> |
  <%= link_to 'İletişim Sayfası', contact_page_path %> |
  <%= link_to 'Yazılar',  posts_index_path %> |
  <%= link_to 'Kategoriler',  categories_path %>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AB17Blog</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "layouts/header" %>
    <%= yield %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </body>
</html>

app/views/pages/contact.html.erb
<% unless @params.nil? %>
  Name: <%= @params['name'] %>
<% end %>

<%= form_for contact_post_path, method: :post, html: { class: 'selam' }  do |f| %>
  <%= f.text_field  :name,      placeholder: 'Adınız' %>
  <%= f.text_field  :surname,   placeholder: 'Soyadınız' %>
  <%= f.email_field :email,     placeholder: 'Email Adresiniz' %>
  <%= f.phone_field :phone,     placeholder: 'Telefon Numaranız' %>
  <%= f.text_area   :message,   placeholder: 'Mesajınız' %>
  <%= f.submit %>
<% end %>

app/views/pages/index.html.erb
<p>Merhaba</p>
<p>Bugünün Tarihi: <%= @today %></p>

app/views/posts/_form.html.erb
<% if @post.errors.any? %>
  <ul>
    <% @post.errors.full_messages.each do |error| %>
      <li><%= error %></li>
    <% end %>
  </ul>
<% end %>
<%= form_for @post do |f| %>
    <%= f.text_field :title, placeholder: 'Başlık' %>
    <%= f.text_area :content, placeholder: 'İçerik' %>
    <%= f.number_field :rating, placeholder: 'Derecelendirme' %>
    <%= f.submit "Enter" %>
<% end %>

app/views/posts/edit.html.erb
<h1>Yazıyı Düzenle</h1>
<% if @post.errors.any? %>
    <p>
    <%= @post.errors.full_messages %>
    </p>
<% end %>
<%= form_for @post, url: posts_update_path do |f| %>
    <%= f.text_field :title, placeholder: 'Başlık' %>
    <%= f.select :category_id, @categories %>
    <%= f.text_field :content, placeholder: 'İçerik' %>
    <%= f.text_field :rating, placeholder: 'Derecelendirme' %>
    <%= f.submit "Enter" %>
<% end %>

app/views/posts/index.html.erb
<h1>Yazılar</h1>
<%= link_to 'Yeni Yazı Ekle', posts_new_path %>
<% @posts.each do |post| %>
<p>
        Başlık: <%= link_to post.title, posts_show_path(post.slug) %><br/>
        Kategori: <%= link_to post.category.name, category_path(post.category) %><br/>
        İçerik: <%= post.content %><br/>
        Oluşturulma Tarihi: <%= post.created_at %><br/>
        Güncellenme Tarihi: <%= post.updated_at %>
    <%= link_to "Düzenle", posts_edit_path(post.slug) %>
    <%= link_to "Sil", posts_destroy_path(post.slug), method: :delete, data:{ confirm: "Silmek istediğinize emin misiniz?" } %>
</p>
<% end %>

app/views/posts/new.html.erb
<h1>Yeni Kayıt Ekle</h1>
<%= render 'form' %>

app/views/posts/show.html.erb
<h1><%= @post.title %></h1>
<p><%= @post.content %></p>